# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
#url: "http://ghanendra.info"
#baseurl: ""

# Name of website
#title: Ghanendra Singh

# List of links in the navigation bar
# navbar-links:
#   Home: ""
#   Publications: "publications"
#   Resume: "resume"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/yingwei.jpg"

theme: jekyll-theme-minimal
title: Ghanendra Singh
#tags: [personal, public]
thumbnail-img: "images/photo.jpg"
description: Personal Homepage
# Site wide configuration

#title: Website of Ghanendra Singh
#theme: jekyll-theme-minimal
#locale: en_US
logo: "images/photo.jpg"

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
# author:
#   name: Yingwei LI
#   email: "yingwei.li@jhu.edu"
#   github: LiYingwei    # eg. daattali
#   #linkedin:

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: false
  google-plus: false
  github: false
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false
  



# # filename of a logo image that has been placed into your images directory

# # Enter the following platform usernames if you would like for them to appear on your site.
# owner:
#   name: Ghanendra
#   avatar: bio-photo.jpg
#   bio: "This is a sample Jekyll academic website."
#   email: 22ghanendra@gmail.com
#   # Do not include the @ symbol in your Twitter username
#   twitter: 22ghanendra
#   linkedin: #username
#   github: Ghanendra19213
#   google:
#     scholar: #id
